// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp1nKH5H_9-vlDUM-6SGYPA3MdYJs5ZaQ',
    appId: '1:704405778968:web:6d2cc4e32b613e628f496d',
    messagingSenderId: '704405778968',
    projectId: 'necxa-finance',
    authDomain: 'necxa-finance.firebaseapp.com',
    storageBucket: 'necxa-finance.firebasestorage.app',
    measurementId: 'G-37P2W8Y5Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPejXWgNYxECaWO8w3n8yP0x_26pnJIvI',
    appId: '1:704405778968:android:2a8274618ecf80088f496d',
    messagingSenderId: '704405778968',
    projectId: 'necxa-finance',
    storageBucket: 'necxa-finance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArqNYRK-DqOXBXjxj6AbUtJtiSXcYNO8c',
    appId: '1:704405778968:ios:ee69d4f65a4e951e8f496d',
    messagingSenderId: '704405778968',
    projectId: 'necxa-finance',
    storageBucket: 'necxa-finance.firebasestorage.app',
    iosBundleId: 'com.example.necxaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp1nKH5H_9-vlDUM-6SGYPA3MdYJs5ZaQ',
    appId: '1:704405778968:web:593089a4b903f4118f496d',
    messagingSenderId: '704405778968',
    projectId: 'necxa-finance',
    authDomain: 'necxa-finance.firebaseapp.com',
    storageBucket: 'necxa-finance.firebasestorage.app',
    measurementId: 'G-6BHXE5001J',
  );
}
